apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-radius
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.strategy.maxSurge }}
      maxUnavailable: {{ .Values.strategy.maxUnavailable }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-radius
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-radius
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
      containers:
        - name: radius
          image: {{ .Values.image.radius }}
          ports:
            - containerPort: 1812
              protocol: UDP
          resources:
            requests:
              cpu: {{ .Values.resources.radius.requests.cpu | quote }}
              memory: {{ .Values.resources.radius.requests.memory | quote }}
            limits:
              cpu: {{ .Values.resources.radius.limits.cpu | quote }}
              memory: {{ .Values.resources.radius.limits.memory | quote }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
            - secretRef:
                name: {{ default (printf "%s-secrets" .Release.Name) .Values.secrets.existingSecret }}
