{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ default (printf "%s-secrets" .Release.Name) .Values.externalSecrets.target.name }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name | quote }}
    kind: {{ .Values.externalSecrets.secretStore.kind | quote }}
  target:
    name: {{ default (printf "%s-secrets" .Release.Name) .Values.externalSecrets.target.name }}
    creationPolicy: {{ .Values.externalSecrets.target.creationPolicy | quote }}
  data:
    {{- range $key, $value := .Values.externalSecrets.data }}
    - secretKey: {{ $key | quote }}
      remoteRef:
        key: {{ $value | quote }}
    {{- end }}
{{- end }}
