{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  DB_URL: {{ .Values.secrets.DB_URL | quote }}
  REDIS_URL: {{ .Values.secrets.REDIS_URL | quote }}
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET | quote }}
  ADMIN_JWT_SECRET: {{ .Values.secrets.ADMIN_JWT_SECRET | quote }}
  RADIUS_SECRET: {{ .Values.secrets.RADIUS_SECRET | quote }}
  EXPRESS_MOBILE_URL: {{ .Values.secrets.EXPRESS_MOBILE_URL | quote }}
  EXPRESS_MOBILE_KEY: {{ .Values.secrets.EXPRESS_MOBILE_KEY | quote }}
  FCM_SERVER_KEY: {{ .Values.secrets.FCM_SERVER_KEY | quote }}
{{- end }}
