{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-api
  namespace: {{ .Values.monitoring.namespace | quote }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-api
  endpoints:
    - path: /metrics
      port: http
      interval: 30s
{{- end }}
