apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-radius
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-radius
  ports:
    - port: 1812
      targetPort: 1812
      protocol: UDP
