apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-secrets
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: api-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_URL
      remoteRef:
        key: secret/data/2fa#DB_URL
    - secretKey: REDIS_URL
      remoteRef:
        key: secret/data/2fa#REDIS_URL
    - secretKey: JWT_SECRET
      remoteRef:
        key: secret/data/2fa#JWT_SECRET
    - secretKey: ADMIN_JWT_SECRET
      remoteRef:
        key: secret/data/2fa#ADMIN_JWT_SECRET
    - secretKey: RADIUS_SECRET
      remoteRef:
        key: secret/data/2fa#RADIUS_SECRET
    - secretKey: EXPRESS_MOBILE_URL
      remoteRef:
        key: secret/data/2fa#EXPRESS_MOBILE_URL
    - secretKey: EXPRESS_MOBILE_KEY
      remoteRef:
        key: secret/data/2fa#EXPRESS_MOBILE_KEY
    - secretKey: FCM_SERVER_KEY
      remoteRef:
        key: secret/data/2fa#FCM_SERVER_KEY
